[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/catppuccin/catppuccin-latte.toml"]

# All key-value pairs in the [env] section will be added as environment variables for any process
# spawned by Alacritty, including its shell. Some entries may override variables set by alacritty itself.
[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
startup_mode = "Maximized"
blur = true
opacity = 0.7
option_as_alt = "Both"
decorations = "None"
dynamic_title = true
padding = { x = 10, y = 10 }
# dimensions = { columns = 135, lines = 50 }

[font]
size = 16.0
bold = { family = "CaskaydiaCove Nerd Font", style = "Bold" }
bold_italic = { family = "CaskaydiaCove Nerd Font", style = "SemiBold" }
italic = { family = "CaskaydiaCove Nerd Font", style = "SemiLight" }
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }

[colors]
draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[cursor]
style = { shape = "Underline", blinking = "On" }
unfocused_hollow = true

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]

[[hints.enabled]]
hyperlinks = true
command = "open"

# Key bindings
#
# Each binding is defined as an object with some properties. Most of the
# properties are optional. All of the alphabetical keys should have a letter for
# the `key` value such as `V`. Function keys are probably what you would expect
# as well (F1, F2, ..). The number keys above the main keyboard are encoded as
# `Key1`, `Key2`, etc. Keys on the number pad are encoded `Number1`, `Number2`,
# etc.  These all match the glutin::VirtualKeyCode variants.
#
# A list with all available `key` names can be found here:
# https://docs.rs/glutin/*/glutin/enum.VirtualKeyCode.html#variants
#
# Possible values for `mods`
# `Command`, `Super` refer to the super/command/windows key
# `Control` for the control key
# `Shift` for the Shift key
# `Alt` and `Option` refer to alt/option
#
# mods may be combined with a `|`. For example, requiring control and shift
# looks like:
#
# mods: Control|Shift
#
# The parser is currently quite sensitive to whitespace and capitalization -
# capitalization must match exactly, and piped items must not have whitespace
# around them.
#
# Either an `action`, `chars`, or `command` field must be present.
#   `action` must be one of `Paste`, `PasteSelection`, `Copy`, or `Quit`.
#   `chars` writes the specified string every time that binding is activated.
#     These should generally be escape sequences, but they can be configured to
#     send arbitrary strings of bytes.
#   `command` must be a map containing a `program` string, and `args` array of
#     strings. For example:
#     - { ... , command: { program: "alacritty", args: ["-e", "vttest"] } }
[keyboard]
bindings = [
    # ⌘ + enter puts window in macOS full screen
    { key = "Enter", mods = "Command", action = "ToggleFullscreen"},
    # opt + right and left jump between words
    { key = "Right", mods = "Alt", chars = "\u001BF" },
    { key = "Left",  mods = "Alt", chars = "\u001BB" },
  #{ key = "H", mods = "Command", chars = "\x02\x68"}
]
